---
abstract: 'Preprocess Pandoc before Processing Pandoc'
author:
  - 'DBR <dbr@cpan.org>'
build_requires:
  Carp: 0
  ExtUtils::MakeMaker: 0
  File::Spec::Functions: 0
  List::Util: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::CheckDeps: 0.006
  Test::More: 0.94
  Test::UseAllModules: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-pandoc-preprocess
provides:
  App::pandoc::preprocess:
    file: lib/App/pandoc/preprocess/Checks.pm
    version: v0.3.1
  App::pandoc::preprocess::File:
    file: lib/App/pandoc/preprocess/File.pm
    version: v0.3.1
requires:
  Data::Printer: 0
  FindBin: 0
  Moo: 0
  MooX::Options: 0
  MooX::Types::MooseLike::Base: 0
  Path::Class: 0
  lib: 0
  namespace::clean: 0
  perl: v5.14.0
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/xdbr/p5-App-pandoc-preprocess
  repository: https://github.com/xdbr/p5-App-pandoc-preprocess.git
version: 0.3.1
x_authority: cpan:DBR
